services:
  deeplx:
    image: missuo/deeplx:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    # environment:
    #   - TOKEN=helloworld  
    #   - DL_SESSION=xxxxxx
    ports:
      - ${HOST_IP}:${DEEPLX_API_PORT}:1188
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true