name: Sync to CNB
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Sync to CNB Repository
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/btpanel/apphub.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="cnb" \
            -e PLUGIN_PASSWORD=${{ secrets.CNB_GIT_PASSWORD }} \
            -e PLUGIN_BRANCH="main" \
            -e PLUGIN_GIT_USER="aingdesk" \
            -e PLUGIN_GIT_EMAIL="support@bt.cn" \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync
